### PR TITLE
Delegate jinja2 templates to Lilya

### PR DESCRIPTION
**Pull request by tarsil**
### Checklist

- [x] The code has 100% test coverage.
- [x] The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
- [x] I branched out from the latest main or is a sub-branch.

## Summary

This basically removes the jinja2 template system from Esmerald and implements the native from Lilya as it is more complete avoiding redundancy in terms of code + allows to use what Lilya has to offer.

This also updates the TemplateConfig allowing to pass more parameters which match the ones in Jinja2. In terms of compatibility, we added those in mako even if mako does not necessarily use them.

### CODE REVIEW

**Review by PeterChain — APPROVED** [review]

**Comment by rona901** [comment]
Give me my data back and my gmail !! This is gmail of animal shelter ! And my money back after damage to my devices

**Comment by rona901** [comment]
Why you guys help him is my account he is phishing

**Comment by rona901** [comment]
I don't understand all this cod's I've never been here. He Hesse wipe all my data. Lock my devices they now in technically . Gmail that used me for all 10 years . I don't know . Facebook that provid 50 shelter dogs . You can check ליליה קושניר Facebook . All week I'm on stress cuz of this. And I don't know how to recovery all this cod's I don't read Payton . Even broke to my iPad

**Comment by rona901** [comment]
***@***.***

**Comment by rona901** [comment]
> ### Checklist
> * [x]  The code has 100% test coverage.
> * [x]  The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
> * [x]  I branched out from the latest main or is a sub-branch.
> 
> ## Summary
> This basically removes the jinja2 template system from Esmerald and implements the native from Lilya as it is more complete avoiding redundancy in terms of code + allows to use what Lilya has to offer.
> 
> This also updates the TemplateConfig allowing to pass more parameters which match the ones in Jinja2. In terms of compatibility, we added those in mako even if mako does not necessarily use them.

Help  he stole my idinty

**Comment by tarsil** [comment]
> > ### Checklist
> > 
> > * [x]   The code has 100% test coverage.
> > * [x]   The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
> > * [x]   I branched out from the latest main or is a sub-branch.
> > 
> > ## Summary
> > This basically removes the jinja2 template system from Esmerald and implements the native from Lilya as it is more complete avoiding redundancy in terms of code + allows to use what Lilya has to offer.
> > This also updates the TemplateConfig allowing to pass more parameters which match the ones in Jinja2. In terms of compatibility, we added those in mako even if mako does not necessarily use them.
> 
> Help he stole my idinty

Who is "he"?

**Pull request merged**
